config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/cocktails/:cocktail_id/doses', to: "doses#create"
  resources :cocktails, only: [:index, :new, :create, :show, :destroy] do
    resources :doses, only: [:new, :create]
  end
    resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, presence: true, uniqueness: {
    scope: :ingredient_id,
    message: 'Already added'
  }
  validates :ingredient_id, presence: true
end
# https://guides.rubyonrails.org/active_record_validations.html#uniqueness

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: params[:id])
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    # raise
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1497644083578-611b798c60f3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60);">
  <div class="container">
    <h1>Mister Cocktails  <strong>batch-329</strong> to <strong>creative people</strong>!</h1>
    <p>Enjoy yourself - meet your bubby here</p>
  </div>
</div>

<div class="container mt-5">

  <!-- <h2>Cocktails</h2> -->
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-12">
         
          <div class="cards" mt-3>
            <% @cocktails.each do |cocktail|  %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
                <%= cl_image_tag cocktail.photo, height: 150, width: 250, crop: :fill %>
                <%= link_to cocktail.name, cocktail_path(cocktail) %>
              </div>
            <% end %>

          </div>
</div>

<div>
<%= link_to "Add a new cocktail", new_cocktail_path %>
</div>
  

app/views/cocktails/new.html.erb
<h1>Add your new cocktail</h1>
<%= simple_form_for(@cocktail) do |f|%>
<%= f.input :name %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Cocktail details</h1>

<h3><%= @cocktail.name %></h3>
<% if @cocktail.photo.present? %>
  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
<% end %>

<div>
  <ul> 
    <% @doses.each do |dose| %>
    <li><%= dose.description %> <%= link_to "Delete", dose_path(dose), method: :delete %></li>
    <% end %>
  </ul>
</div>

<div class="add-dose">
<%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %>
</div>

<div>
<%= link_to "Back to cocktails list", cocktails_path %>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>